spring:
  profiles:
    active: #profiles.active#
server:
  port: 30007

  config: classpath:logback-boot.xml  # 默认logback.xml配置文件目录
  level:
    com.mukutech.seapersonservice.mapper: debug  #打印sql


mybatis-plus:
  global-config:
    id-type: 1
    logic-delete-field: delFlag
    logic-delete-value: 1
    logic-not-delete-value: 0
  mapper-locations: classpath:/mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-aliases-package: com.mukutech.seapersonservice.pojo.entity

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 6000 # feign 的超时设置
        readTimeout: 6000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 设置hystrix的超时时间为3000ms, 之后才调用降级方法